### ISSUE TITLE
Getting Error while running example snippets

### ISSUE THREAD

**Issue by Karn3003** [tunakasif/torch-frft#8]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-c919df3e08d0>](https://localhost:8080/#) in <cell line: 8>()
      6 a = 0.5
      7 X = torch.rand(N, N)
----> 8 Y1 = frft(X, a) # equivalent to dim=-1
      9 Y2 = frft(X, a, dim=0)

[/usr/local/lib/python3.10/dist-packages/torch_frft/frft_module.py](https://localhost:8080/#) in frft(fc, a_param, dim)
     13 
     14     # 4-modulation and shifting to [-2, 2] interval
---> 15     a = torch.fmod(a_param, 4)
     16     if a > 2:
     17         a -= 4

TypeError: fmod() received an invalid combination of arguments - got (float, int), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, Number other, *, Tensor out)

**Comment by Karn3003** [comment]
Yeah, I think I figured it out. the order should be tensor. Please change the readme file.
Btw thanks for implementing the frft in Pytorch.

**Comment by tunakasif** [comment]
Hey @Karn3003, thank you for noticing and you are correct, currently the fractional order needs to be a `torch.Tensor` for `frft()`, but it can be a `float` for `dfrft()`. In future updates it will support `float` for `frft()` as well. Please refer to the `README.md` of `dev` branch for now.

**Comment by Karn3003** [comment]
Hi @tunakasif ,
Can you share some resources for FrFT. As I am new to this it would be helpful if you could share some resources. Also can you please let me know the difference between Continous and Discrete FrFT as they both produce the same shape transformation for a given order? Also if I do FrFT layer in my model which learns the order then for inverse I need to do negative order to get back the original signal back right??
